[package]
name = "another_ext4"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.2.1"
log = "0.4"
spin = { version = "0.9", optional = true }
[features]
block_cache = ["dep:spin"]
fuser_root_inode = []